apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - serviceaccount.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/name: genesis-api
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: genesis-protocol
