apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cronjob-episode-gen.yaml
  - serviceaccount.yaml

commonLabels:
  app.kubernetes.io/name: genesis-agents
  app.kubernetes.io/component: batch
  app.kubernetes.io/part-of: genesis-protocol
